# Generated by Django 5.2.1 on 2025-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_date', models.DateField(verbose_name='Ngày dương lịch')),
                ('lunar_date', models.CharField(max_length=20, verbose_name='Ngày âm lịch')),
                ('pl_time', models.CharField(blank=True, max_length=20, verbose_name='Giờ PL')),
            ],
        ),
    ]
